### ISSUE TITLE
Batch resolver with parameters can't find different parameters for the batch

### ISSUE THREAD

**Issue by mauricioszabo** [wilkerlucio/pathom3#105]
Provided that I have a resolver that increments a number, given a specific param (for example, the number that the parameter should be incremented):

```clojure
(let [idx (connect/resolver
           'increments
           {::connect/input [:number]
            ::connect/output [:incr-number]
            ::connect/batch? true}
           (fn [env numbers]
             (map (fn [{:keys [number]}] 
                    {:incr-number (+ number (:inc (connect/params env)))})
                  numbers)))]
  (eql/process (idx/register idx)
               {:plus-1 [{:number 1} {:number 2}]
                :plus-2 [{:number 3} {:number 4}]}
               [{:plus-1 [:number '(:incr-number {:inc 1})]}
                {:plus-2 [:number '(:incr-number {:inc 2})]}]))
```

This EQL results in:
```clojure
{:plus-1 [{:number 1, :incr-number 3} {:number 2, :incr-number 4}], 
 :plus-2 [{:number 3, :incr-number 5} {:number 4, :incr-number 6}]}

;; :plus-1 should be: [{:number 1, :incr-number 2} {:number 2, :incr-number 3}]
```

The batch can't "see" that `params` is expected to be different for inputs `{:number 1}, {:number 2}` and `{:number 3}, {:number 4}`.

What I found is that, at the time this resolver is called, there's only a single place on the `env` that tells me `{:inc 1}` exists - on key `:com.wsscode.pathom3.connect.runner/root-query`. After the query ran, I can also see the it on `:com.wsscode.pathom3.connect.runner/resolver-cache*`.

I see two possible solutions: either `(connect/params)` returns a list of params for each input (so we can `(map ... inputs params)` and see the individual params, or even `group-by` in some way) or batch can be called only for queries with the same params. The first solution could make batches harder to implement; at the second, batches' implementations will not change at all (but for situations were we can batch everything, and apply the params on the results - that means, the most expensive operation is not dependent on params at all, we'll lose the ability to aggressive batch).

So... WDYT?

**Comment by wilkerlucio** [comment]
Hello, I'm taking a look at it now, I believe this in this case is better to split the batches and have batches with different params running in different calls, seems a more general solution to me.

**Comment by mauricioszabo** [comment]
Maybe related: https://github.com/wilkerlucio/pathom3/discussions/66
