### ISSUE TITLE
Spec failure on union query for a subset of types known to a resolver

### ISSUE THREAD

**Issue by rcdomigan** [wilkerlucio/pathom3#110]
Hi, I was writing a query for a subset of the types known to a union resolver. I expected to get a list back with only the types I queried for, but I instead a spec error is printed out and empty maps are returned for types which are not included in the query

Modifying an example from the pathom3 docs:

```clojure
(def union-env
  (pci/register
    [(pbir/single-attr-resolver :acme.post/title :acme.post/link #(str % "-link"))
     (pbir/single-attr-resolver :acme.ad/x :acme.ad/y inc)
     (pbir/constantly-resolver :acme/feed
       [^{:com.wsscode.pathom3.format.eql/union-entry-key :acme.post/id}
        {:acme.post/title "TITLE"}
        ^{:com.wsscode.pathom3.format.eql/union-entry-key :acme.ad/id}
        {:acme.ad/x 1}
        ])]))

(p.eql/process union-env
  [{:acme/feed
    {:acme.post/id [:acme.post/link]
     ;; I just want posts, so omit the :acme.ad/id
     ;; :acme.ad/id   [:acme.ad/y]
     }}])
; => #:acme{:feed [#:acme.post{:link "TITLE-link"} {}]}
```
I didn't expect to get an empty map for the :acme.ad/id. I think I'd expect an empty map for a query like `:acme.ad/id []`. I think either query should be valid, if for no other reason than reducing coupling between remotes.

The spec failure looks like:
```
com/wsscode/pathom3/connect/runner.cljc:1004 run-graph!'s argument list
-- Spec failed --------------------

  [{:com.wsscode.pathom3.connect.runner/batch-pending*
    #<Volatile@7ebbe79c: {}>,
    :com.wsscode.pathom3.connect.indexes/index-oir
... ~200 lines of map content ...
   nil
   ^^^
   #<Atom@1fd3ce23: {:acme.ad/x 1}>]

should satisfy

  map?

-- Relevant specs -------

:com.wsscode.pathom3.connect.planner/graph:
  (clojure.spec.alpha/keys
   :req
   [:com.wsscode.pathom3.connect.planner/nodes])
:edn-query-language.ast/node:
  (clojure.spec.alpha/multi-spec edn-query-language.core/node-type :type)

-------------------------
Detected 1 error

java.lang.AssertionError: 
 at com.fulcrologic.guardrails.core$callsite_exception.invokeStatic (core.cljc:616)
    com.fulcrologic.guardrails.core$callsite_exception.invoke (core.cljc:616)
    com.wsscode.pathom3.connect.runner$run_graph_BANG_.invokeStatic (runner.cljc:1004)
... more stack trace ...
```

I'm using c456c7b5c8e0ee6e12a4b755cfb8b23fbfda8652 on clojure 1.10.3

If this is working as intended, I think the error message and/or docs should make it clear we ought to query for all possible types in the union and then deal with some possibly empty maps.

Thanks for you time

**Comment by rcdomigan** [comment]
My particular use case is similar to the feed. I guess the resolver could inspect the input query and use that to modify it's call to the database. I think that takes me into dynamic query territory.

**Comment by wilkerlucio** [comment]
Hello @rcdomigan , sorry the delay on this.

Just checking it now, I think you are right, there was no appropriate handling of unions missing branches. Fixing it now.
