### ISSUE TITLE
::pco/output on mutations

### ISSUE THREAD

**Issue by awkay** [wilkerlucio/pathom3#112]
If a mutation outputs a map that has keys that are not defined anywhere in a resolver, the attribute error mechanism is still triggered to indicate that the attributes are unreachable (even though the mutation's return value includes them).

**Comment by wilkerlucio** [comment]
Are you declaring the output of the mutation?

**Comment by awkay** [comment]
Let me make a repro...thanks for looking

**Comment by awkay** [comment]
Must have been a code reload problem. I wrote a small repro example myself and it works fine for me too. Sorry for the noise.
