### ISSUE TITLE
For the same transaction, resolver is called multiple times (even if we have the same inputs) for a foreign environment. 

### ISSUE THREAD

**Issue by pfeodrippe** [wilkerlucio/pathom3#119]
I'm seeing some differences in the planner between a local environment and a foreign one (which still is experimental according to the docs, so it's expected), some resolvers for the last are being run twice when while once for the first, see comments below.

```clojure
(pco/defresolver a->b [{:keys [a/id]}]
  {:b/id 1
   :b/name 2})

(pco/defresolver b->address [{:keys [b/id b/name]}] ;; These arguments are important, see the next code block.
  #:address{:zip-code (println :>>>>ADDRESS)
            :name "address 1"})

(def env-local
  (pci/register
   [a->b
    b->address]))
;; `(println :>>>>ADDRESS)` is run only once.

(p.eql/process env-local
               {:a/id 1}
               [:address/name
                :address/zip-code])

(def env-foreign
  (pci/register (concat [(pcf/foreign-register (p.eql/boundary-interface env-local))])))

(p.eql/process env-foreign
               {:a/id 1}
               [:address/name
                :address/zip-code])
;; `(println :>>>>ADDRESS)` is run twice (one per each `:addres/.*` field requested).
``` 

```clojure
...

;; When I change only `b->address` to require less input (just ` :b/id` in this case), it works normally again.
(pco/defresolver b->address [{:keys [b/id}] 
  #:address{:zip-code (println :>>>>ADDRESS)
            :name "address 1"})
...

(p.eql/process env-foreign
               {:a/id 1}
               [:address/name
                :address/zip-code])
;; `(println :>>>>ADDRESS)` is run only once, same behavior as running it with the local env.
```

**Comment by wilkerlucio** [comment]
Hello, thanks for the report, I was able to reproduce and I can see this is something that needs better optimization on the planner, the case is an AND node with a single branch and a next node pointing to the same resolver, those must be collapsed.

<img width="468" alt="Screen Shot 2022-01-09 at 21 33 33" src="https://user-images.githubusercontent.com/25736/148707511-0ed4ac49-26e0-4b2f-950a-6815fe4832fc.png">

**Comment by wilkerlucio** [comment]
@pfeodrippe I imagine you had a bigger case that ended up in this result, can you please confirm the fix? If not fixed open re-open this issue.

**Comment by pfeodrippe** [comment]
Hi @wilkerlucio, thanks for the fix! The code at https://github.com/wilkerlucio/pathom3/issues/119#issue-1097276585 is having the same behavior though, let me know if I can help with something o/ 

I'm using `[com.wsscode/pathom3 "2022.01.09-alpha"]`.

**Comment by wilkerlucio** [comment]
The fix isn't released yet, to try it you need to use the version from master.

**Comment by wilkerlucio** [comment]
And sorry if you checked from the CHANGELOG, I just realized I add the updates at the wrong version there 🤦

**Comment by pfeodrippe** [comment]
Oh yeah, thank you man for this work o/

**Comment by pfeodrippe** [comment]
Yes, now it's working, thank you very much, WIlker o/
