### ISSUE TITLE
Pathom3 + Walkable?

### ISSUE THREAD

**Issue by den1k** [wilkerlucio/pathom3#132]
Can [Walkable](https://walkable.gitlab.io/walkable/1.3.0/installation.html) and Pathom3 work together?

**Comment by wilkerlucio** [comment]
Not in the current state, this is more an issue for making in the Walkable project, the integration needs to use the features from dynamic resolves to allow query delegation so you can use it in combination with other Pathom 3 resolvers.

**Comment by den1k** [comment]
Got it. Thanks!
