### ISSUE TITLE
Smart maps in ClojureScript

### ISSUE THREAD

**Issue by keerts** [wilkerlucio/pathom3#133]
Are smart-maps usable in ClojureScript? There is no async namespace like for eql. When attempting to use I get a result like this. 

```
{:com.wsscode.pathom3.connect.runner/attribute-errors {:tracket/worklogs {:com.wsscode.pathom3.error/cause :com.wsscode.pathom3.error/node-errors, :com.wsscode.pathom3.error/node-error-details {2 {:com.wsscode.pathom3.error/cause :com.wsscode.pathom3.error/node-exception, :com.wsscode.pathom3.error/exception #error {:message Resolver avisi.wow.tracket/worklogs returned an invalid response: #<Promise[~]>, :data {:response #<Promise[~]>}}}}}}}
=> nil
```

**Comment by wilkerlucio** [comment]
Hello @keerts.

Unfortunately, smart maps don't support async, neither in Clojure or ClojureScript.

Closing this for now, but if you like to keep a conversation on it, please open a discussion with some thoughts and we can talk more about it.

**Comment by keerts** [comment]
Didn't know about discussions, that's indeed a better option for questions like this.

Too bad Smart Maps don't support async, it's such a great idea and much fun!
