### ISSUE TITLE
Optional key throws "All paths from an OR node failed"

### ISSUE THREAD

**Issue by dehli** [wilkerlucio/pathom3#138]
Hi, as always thanks for all your work w/ pathom! I've run into a bug w/ pathom3 and optionality. When there are more than one resolvers that conditionally return a key, and none of them return the optional key you're requesting, you'll get an exception thrown (instead of the key not returning). I was able to replicate this behavior w/ the latest SHA. I've got a failing test on my fork in case that can save you some time (https://github.com/wilkerlucio/pathom3/compare/main...dehli:main).

```clj
(ns dev.dehli.pathom3.all-paths-failed
  (:require [com.wsscode.pathom3.connect.indexes :as pci]
            [com.wsscode.pathom3.connect.operation :as pco]
            [com.wsscode.pathom3.interface.eql :as p.eql]))

(pco/defresolver resolver-a
  [{in :in}]
  {::pco/output [:out]}
  (when (= in "a")
    {:out "A"}))

(pco/defresolver resolver-b
  [{in :in}]
  {::pco/output [:out]}
  (when (= in "b")
    {:out "B"}))

(def env
  (pci/register [resolver-a resolver-b]))

(comment
  (p.eql/process-one env {:in "a"} (pco/? :out)) ;; => "A"
  (p.eql/process-one env {:in "b"} (pco/? :out)) ;; => "B"
  (p.eql/process-one env {:in "c"} (pco/? :out)) ;; => All paths from an OR node failed. Expected: {:out {}}
  )
```

A full project showcasing this example is [here](https://github.com/dehli/pathom-edge-cases/tree/6b88d58cad4903d2f3cad9fe43159a3484250df1/pathom3/all-paths-failed).

Thanks!

**Comment by wilkerlucio** [comment]
Thanks for the repro, I confirmed the issue.

**Comment by wilkerlucio** [comment]
hello @dehli, I just pushed a possible fix to main, can you please confirm to me it fixes the issue in your scenario?

**Comment by dehli** [comment]
Closing as your fix did address my issue. Thanks again!
