### ISSUE TITLE
Nested nested inputs

### ISSUE THREAD

**Issue by danskarda** [wilkerlucio/pathom3#144]
Hello,
first let me express my thank you for the project. Pathom is an excellent idea and I see a lot of potential.

Today I played a little bit with nested inputs and found some strange behavior. I will start with (working) example from documentation, ie :game/top-players-avg-score.

```clojure
(pco/defresolver top-players
  "Return maps with ids for the top players in a given game."
  []
  {:game/top-players
   [{:player/id 2}
    {:player/id 3}]})
```

I removed some players from the game to make output shorter. Then I add one more level to `:player/score` and make it `{:player/scores [:score/points]}` (whatever it means)

```clojure
(pco/defresolver player-by-id
  "Get player by id, in our case just generate some data based on the id."
  [{:keys [player/id]}]
  {:output [:player/name {:player/score [:score/points]}]}
  {:player/name (str "Player " id)
   :player/score (map #(hash-map :score/points %) (range 1 id))})
```
Let's check it works:

```clojure
(eql/process (pci/register [top-players player-by-id])
             [{:game/top-players [:player/name {:player/score [:score/points]}]}])
;; => #:game{:top-players [#:player{:name "Player 2", :score (#:score{:points 1})} #:player{:name "Player 3", :score (#:score{:points 1} #:score{:points 2})}]}
```
Now let's write update top-players-avg. I use same edn query as in above test (only without :player/name)

```clojure
(pco/defresolver top-players-avg
  "Compute the average score for the top players using nested inputs."
  [{:keys [game/top-players]}]
  {::pco/input [{:game/top-players [{:player/score [:score/points]}]}]}
  {:game/top-players-avg-score
   (let [scores (->> top-players (mapcat :player/score) (map :score/points))
         score-sum (apply + scores)]
     (double (/ score-sum (count scores))))})
```

Let's test it with data from our test:
```clojure
(eql/process  (pci/register [top-players player-by-id top-players-avg])
              #:game{:top-players [#:player{:name "Player 2", :score [#:score{:points 1}]} #:player{:name "Player 3", :score [#:score{:points 1} #:score{:points 2}]}]}
              [:game/top-players-avg-score])
;; => #:game{:top-players-avg-score 1.333333333333333}
```

Final test which test if Pathom is able to resolve nested nested data fails:
```clojure
(eql/process (pci/register [top-players player-by-id top-players-avg])
             [:game/top-players-avg-score])
;;; BANG! 
;;   Pathom can't find a path for the following elements in the query:
;;  [:score/points] at path [:game/top-players]
```

Computation from nested nested data works. When I ask eql/process for nested nested data it works. But when resolver asks for same nested nested data it fails. Is it a bug, expected behavior or am I doing something wrong?

Thank you!

**Comment by wilkerlucio** [comment]
Hello @danskarda, thanks for the input, I tested it out, I found the issue is in your `player-by-id` resolver, the key `:output` on config is wrong, it must be `::pco/output`, doing that change makes the last example work as expected. Please re-open the issue if you still see an issue.
