### ISSUE TITLE
:com.wsscode.pathom3.error/attribute-missing vs :com.wsscode.pathom3.error/missing-output

### ISSUE THREAD

**Issue by wilkerlucio** [wilkerlucio/pathom3#149]
Seems like those attributes conflict for the same purpose, must be checked and if it's the case, remove one of them, otherwise get docs explaining the distinction.

**Comment by souenzzo** [comment]
There is no `:com.wsscode.pathom3.error/missing-output` in  `com.wsscode.pathom3.error-test`

**Comment by wilkerlucio** [comment]
I did some digging, and this is the current situation:

- `:com.wsscode.pathom3.error/missing-output` is used when verifying the entity data (happens every time after the graph is ran), if some expected attribute is not present in the output entity, and you are running on strict mode, you will get an error with this cause. This is only case where you will see this error
- `:com.wsscode.pathom3.error/attribute-missing` is used when Pathom is checking for errors in lenient mode, when some attribute is missing, this is the cause that gets used.

After those observations, I think it doesn't make sense to keep both, the question now is just which one to keep, in any case it's gonna be a breaking change for users looking for the one getting removed.

I'm leaning towards keeping `:com.wsscode.pathom3.error/attribute-missing` and remove `:com.wsscode.pathom3.error/missing-output`.

Gonna think a bit more about it, but I plan to make this change soon.
