### ISSUE TITLE
Difference between batched and non-batched behavior. Bug?

### ISSUE THREAD

**Issue by jeremyrsellars** [wilkerlucio/pathom3#173]
(I have been using Pathom3 for a few months now and absolutely love it! Thank you so much.)

I am working on a multilingual project.  We store different strings in the database for English and Spanish, but we may add more languages in the future. Instead of having all the database tables have N=2 fields per string (like title_en, title_es, etc., and then description_en, description_es, etc.), instead, I have a single field like title_resource_id to which the language-specific resources are attached, like:

```edn
 {{:resource-id 1, :language "en"} "Hello",
  {:resource-id 1, :language "es"} "Hola"
  ...}
```

I simplified my project down as far as I could to show how to reproduce the problem.  A git repo for the minimal reproduction steps is [here](https://github.com/jeremyrsellars/pathom-exploration/blob/ebbf76d393de5952193ed8229209c3f8a5793e49/README.md#example-1); the rest of this issue description refers to that example.  It is self-contained, so the "database" is simply hard-coded data in the clojure file.

Note that the resource query is pretty much the same for `title-resource` at both the parent- and child- levels, but it only works at the parent level.  In the real project I am working on, this goes 4 levels deep, not just 2.  My goal is to batch the resource string lookups so there is only 1 lookup (or at most a few lookups), so I want to use batched resolvers, but they don't always return the data they should.

query
---------------

```edn
[{:child-parents
  [:parent/id
   #:parent{:title-resource
            [:lang-resource/rid
             #:lang-resource{:resources [:language/code :lang-resource/value]}]} ; <-- these work
   #:parent{:children
            [:child/id
             :child/title-rid
             #:child{:title-resource                                   ; <-- does not work
                     [:lang-resource/rid                               ; <-- does not work
                      #:lang-resource{:resources                       ; <-- does not work
                                      [:language/code                  ; <-- does not work
                                       :lang-resource/value]}]}]}]}]   ; <-- does not work
```
result
---------------
```edn
{:child-parents
 [#:parent{:id 1,
           :title-resource
           #:lang-resource{:rid 1,
                           :resources
                           [{:language/code :language/en,
                             :lang-resource/value
                             {:language/id 1,
                              :language/code :language/en,
                              :lang-resource/rid 1,
                              :lang-resource/rid-code "en-1",
                              :lang-resource/value "en:1"}}
                            {:language/code :language/es,
                             :lang-resource/value
                             {:language/id 2,
                              :language/code :language/es,
                              :lang-resource/rid 1,
                              :lang-resource/rid-code "es-1",
                              :lang-resource/value "es:1"}}]},
           :children
           [#:child{:id 101, :title-rid 1}                             ; <-- missing :child/title-resource
            #:child{:id 102,
                    :title-rid 3,
                    :title-resource #:lang-resource{:resources
                                                    {}                 ; <-- should be a vector w/ 2 entries
                                                    }}]}]}
```

### Summary

The `:child/title-resource` works unless children-in-parents is batched.

```
(defn lookup-children-by-parent-id
  [id]
  {:parent/children
   [{:child/id (+ 100 id) :parent/id id :child/title-rid 1}
    {:child/id (+ 101 id) :parent/id id :child/title-rid 3}]})

; 2 implementations that should be identical, except one is batched
(pco/defresolver children-in-parents-batched
  "Fetches children in child parents specified by parent/id"
  [_env parents]
  {::pco/input  [:parent/id]
   ::pco/output [{:parent/children child-attributes}]
   ::pco/batch? true}
  (let [parent-ids (map :parent/id parents)]
    (mapv lookup-children-by-parent-id
          parent-ids)))
(pco/defresolver children-in-parents-one
  "Fetches children in child parents specified by parent/id"
  [_env {:keys [parent/id]}]
  {::pco/input  [:parent/id]
   ::pco/output [{:parent/children child-attributes}]}
  (lookup-children-by-parent-id id))

(def resolvers
  (let [show-batch-bug? true]
    [parent-title-resource
     child-title-resource
     (if true resource-value-batched resource-value-one)
     resource-values
     parents
     (if show-batch-bug?
       children-in-parents-batched ; <-- does work in a nested query, but works for direct children
       children-in-parents-one)   ; <-- works
     #_|]))
```

(I wonder if the problem occurs when a query has multiple levels of batched resolvers.)

Am I misusing Pathom3 or is this a bug?

**Comment by jeremyrsellars** [comment]
I think it broke in this [commit](https://github.com/wilkerlucio/pathom3/commit/c81d1c5a53b1604899679c780f5d36a438c8139d#diff-6af1853387f61d86e516ca36756ea90be4b759d1397c7a741d95e8a1ae2730c2R1134) to the planner: c81d1c5a53b1604899679c780f5d36a438c8139d , but I think the problem might be in the runner because the batching doesn't affect the plan.  (I verified this comparing the batched and non-batched environments using `pcp/compute-run-graph` and the output was the same.)

Here's a difference between the same query non-batched
![ex1-one](https://user-images.githubusercontent.com/1396319/210266548-e27b737d-34f1-46d3-a5ff-2e33d7dd3b14.png)
and batched (near the orange lines)
![ex1-batched](https://user-images.githubusercontent.com/1396319/210266562-725124e4-ee9c-4ab9-a8d2-ef7c8a4a1431.png)

**Comment by wilkerlucio** [comment]
Thanks for the great report! It might be related to #169. I'm currently looking at that issue, I'll keep you posted once I dig more into that and here.

**Comment by wilkerlucio** [comment]
I just validated it is just like the but on #169.

Until I figure out a fix for it, you can use the parallel processor. There issue here is related to how pathom coordinates batching on serial processing. The parallel processor uses a different mechanism and doesn't suffer from this issue.

```clojure
; running on parallel processor
@(p.a.eql/process (assoc env ::p.a.eql/parallel? true) query)
```

**Comment by wilkerlucio** [comment]
I just fixed #169, and it ended up being something different. I'll keep investigating this one.

**Comment by yenda** [comment]
I think the issue I reported here https://github.com/wilkerlucio/pathom3/issues/177 might be the same, but I made a smaller repro case.

**Comment by jeremyrsellars** [comment]
I confirm that this has fixed the issue in both my simple case and in my production app.  Thanks for all the help!
