### ISSUE TITLE
Resolvers are not run in parallel with other resolvers

### ISSUE THREAD

**Issue by sirmspencer** [wilkerlucio/pathom3#197]
If I have a query that is X number of "rows", each resolver written to properly work in parallel will run all rows in parallel.  However if more than one parallel resolver is needed, they do not run in parallel together. 

For a little more context, there is an initial resolver that, for example, takes a list of ids and queries the main data set.  Then in that response 4 "columns" need to be resolved further.  Each of those 4 columns goes out to a different server so they can be run in parallel in the sense that the EQL server isn't doing much processing, but waiting on the http requests.  This second step is where I am not seeing any parallelization between resolvers.

EDIT I am seeing the same thing after converting all of the "column" resolvers to bulk resolvers.

**Comment by sirmspencer** [comment]
It might help to point out that the resolvers not running in parallel are bulk resolers.

**Comment by sirmspencer** [comment]
I think this is specific to bulk resolvers the more I look at it.

**Comment by wilkerlucio** [comment]
Closing until more info is provided.
