### ISSUE TITLE
[bug] If a bulk resolver returns a list of length <> input length pahtom hangs

### ISSUE THREAD

**Issue by sirmspencer** [wilkerlucio/pathom3#199]
# Why would this happen?

This happens often when a list contains a value to be looked up from a different system.  In the case where there are some values and some nulls, any api call is going to return the shorter list.  Think "assigned to name" when some items are assigned and some are not.   It is very hard to diagnose all of the async resolvers when pathom just hangs.

# What should happen?

Just like a single resolver that returns nil, a missing path error should be thrown.

**Comment by wilkerlucio** [comment]
Hello @sirmspencer ! Sorry for the delay, can you send me a reproduction example of this issue?

**Comment by sirmspencer** [comment]
Hi @wilkerlucio maybe.  I'm not sure if its still an issue, we figured out some boiler plate for list type resolvers so I have not had an issue in a while.

**Comment by wilkerlucio** [comment]
I'm glad you hear you got it figured, I'm going to close it for now. Feel free to reopen it if the problem arises again.
