### ISSUE TITLE
Implicit resolver priority based on number of input attributes

### ISSUE THREAD

**Issue by MrEbbinghaus** [wilkerlucio/pathom3#202]
(See [Slack Discussion](https://clojurians.slack.com/archives/C87NB2CFN/p1692025696580489?thread_ts=1692007239.025389&cid=C87NB2CFN) for further reference)

Resolvers with higher specificity should get priority over resolvers with less specificity. Specificity can be determined by the number of input attributes. 

## Problem Statement

Given following resolvers
```clojure
(defresolver resolve-full-name-by-first-name [{:keys [first-name]}]
  {:person/full-name first-name})
  
(defresolver resolve-full-name-with-first-and-last-name [{:keys [first-name last-name]}]
  {:person/full-name (str first-name " " last-name)})
```
and this query
```clojure
[([:person/full-name] {:person/first-name "Björn", :person/last-name "Ebbinghaus"})]
```

Currently, the output could be:
```clojure
[{:person/full-name "Björn"}]
; or
[{:person/full-name "Björn Ebbinghaus"}]
```
Since both resolvers could provide `:person/full-name` given the input.

## Possible Solution
Prioritise resolvers with higher specificity. 
This would make pathoms behaviour predictable:
```clojure
; always
[{:person/full-name "Björn Ebbinghaus"}]
```

(This would be a non-breaking change, except if someone depends on the random behaviour.)

**Comment by yenda** [comment]
pathom3 has `pco/?` to make an input optional, so in your example `last-name` should just be an optional input and there should only be one resolver for full-name,
