### ISSUE TITLE
Dynamic Resolvers

### ISSUE THREAD

**Issue by wilkerlucio** [wilkerlucio/pathom3#21]
Dynamic resolvers are a special type of resolver that allows for "sideways batching" in Pathom.

This kind of resolvers enables efficient integration with things like Datomic, GraphQL, SQL, etc... Also a requirement to make Pathom integration with other Pathom graphs, which will enable the [Maximal Graph](https://www.youtube.com/watch?v=IS3i3DTUnAI) vision.

I would say this is 80% there. The hard part of planning around dynamic resolvers has been done for a year, but given the new process design on Pathom 3, the runner part needs a rewrite. I also need to gain more confidence in the planner.

To gain confidence and consider this done, I think we need to have a few working solutions that use dynamic resolvers, this way we can test if it behaves as expected.

Plans of dynamic resolver implementations for Pathom 3:

- [x] Pathom 3 Foreign calls (integration with Pathom itself)
- [ ] [Pathom 3 Datomic](https://github.com/wilkerlucio/pathom3-datomic)
- [ ] [Pathom 3 GraphQL](https://github.com/wilkerlucio/pathom3-graphql)

**Comment by avocade** [comment]
Move `Datomic > GraphQL`… :D

**Comment by wilkerlucio** [comment]
I'll close this issue here, Pathom can already talk to itself, the others we will track on their respective repositories.
