### ISSUE TITLE
The plural of `index` is `indices`, not `indexes`

### ISSUE THREAD

**Issue by edenworky** [wilkerlucio/pathom3#212]
Not sure if this is intentional or has been discussed before, but `indexes` is really throwing me off :sweat_smile: 

I can understand how `indexes` can be more intuitive and it would probably be best to have both with one aliasing the other, but if there's only one it should be `indices` in my opinion.

**Comment by wilkerlucio** [comment]
Hello, this is the first time this is brought here. I went looking and found this article from Bloomberg: https://www.nasdaq.com/articles/indexes-or-indices-whats-the-deal-2016-05-12

According to it, although the indices version is the most used, the indexes version seems to be also acceptable. I'm copying here their nice chart about the usage of the words over the years:

![ec1de43664f0fd975a6406c5602d16d012860189_index20v20indicies_tcm5044-28806](https://github.com/wilkerlucio/pathom3/assets/25736/308406e2-33e2-4763-84d8-05fe38365cea)

I am needly a Brazilian Portuguese speaker, and the term indexes always made sense to me, and I have been using it for years.

Considering what I'm seeing, I won't be changing anything at this time, please feel free to bring more to the discussion if you think we need more.

Thanks for making me aware of this nuance.

**Comment by edenworky** [comment]
Thank you for your response! To me the chart speaks for itself, a lot more people consistently use `indices` over `indexes`. In general, it's a thing to have to remember, I believe that if English supports both then so should clojure.

Linguistically and etymologically (in case anyone cares haha) the `-x` suffix in Latin is a conjoining of `-cs` in Proto-Latin, which in both pluralize as `cēs`, e.g. index/indices, matrix/matrices, etc. Obviously it would break compatibility to remove `indexes`, but I still think adding `indices` as an alias would be an improvement to expressibility overall, but I don't have any more of a reason than what I already said, so I'll defer to your judgement on the subject.
