### ISSUE TITLE
Batch resolvers break stuff

### ISSUE THREAD

**Issue by fjolne** [wilkerlucio/pathom3#30]
Repro:
```clojure
(let [parents  {1 {:parent/children [{:child/id 1}]
                     :parent/plug     {:plug/id 1}}}
        children {1 {:child/ident :child/good}}
        plugs    {1 {:plug/ident :plug/temp}}
        indexes  (pci/register
                   [(pco/resolver `pc
                      {::pco/input  [:parent/id]
                       ::pco/output [:parent/children]
                       ::pco/batch? true}
                      (fn [{:keys [db]} items]
                        (mapv (fn [{:parent/keys [id]}]
                                (select-keys (parents id) [:parent/children]))
                          items)))

                    (pco/resolver `pp
                      {::pco/input  [:parent/id]
                       ::pco/output [:parent/plug]
                       ::pco/batch? true}
                      (fn [{:keys [db]} items]
                        (mapv (fn [{:parent/keys [id]}]
                                (select-keys (parents id) [:parent/plug]))
                          items)))

                    (pco/resolver `ci
                      {::pco/input  [:child/id]
                       ::pco/output [:child/ident]
                       ::pco/batch? true}
                      (fn [{:keys [db]} items]
                        (mapv (fn [{:child/keys [id]}]
                                (select-keys (children id) [:child/ident]))
                          items)))

                    (pco/resolver `pi
                      {::pco/input  [:plug/id]
                       ::pco/output [:plug/ident]
                       ::pco/batch? true}
                      (fn [{:keys [db]} items]
                        (mapv (fn [{:plug/keys [id]}]
                                (select-keys (plugs id) [:plug/ident]))
                          items)))

                    (pco/resolver `pi*
                      {::pco/input  [:parent/plug]
                       ::pco/output [:plug/id]
                       ::pco/batch? true}
                      (fn [{:keys [db]} items]
                        (mapv (fn [{:parent/keys [plug]}] plug)
                          items)))])]
    [(mapv #(p.eql/process indexes {:all-parents [{:parent/id 1}]} [{:all-parents %}])
       [[{:parent/children [:child/ident]}]
        [:plug/ident
         {:parent/children [:child/ident]}]])
     (mapv #(p.eql/process indexes {:parent/id 1} %)
       [[{:parent/children [:child/ident]}]
        [:plug/ident
         {:parent/children [:child/ident]}]])])
```
=>
```clojure
[[{:all-parents [#:parent{:children [#:child{:ident :child/good}]}]}
   {:all-parents [{:plug/ident :plug/temp
                    :parent/children [{}]}]}]
   ;; query directly on parent works fine
   [#:parent{:children [#:child{:ident :child/good}]}
    {:plug/ident :plug/temp, :parent/children [#:child{:ident :child/good}]}]]
```
Expected:
```clojure
[[{:all-parents [#:parent{:children [#:child{:ident :child/good}]}]}
   {:all-parents [{:plug/ident :plug/temp
                    :parent/children [#:child{:ident :child/good}]}]}]
 ;; same
]
```
Tested against latest master commit: cd8f4d05ef2ab3fbb19cec2153d9ce61a8056579

**Comment by wilkerlucio** [comment]
Thanks for the report, I've been investigating some issues with batching, there is a flaw in the current implementation, and I believe you brought one more example of its manifestation. When I did the design for it, the idea was that when the runner hits a batch item, it will pause the processing of that graph and move to the next entity. Once the scan finishes all the entities, it can look at the items collected for batch, process, merge the data back and resume the paused processes.

The pause mechanism works this way:

- A resolver returns a map that contains a token saying the runner should pause.
- The runner sees that, and just stops calling the things to run next, and remembers that batch hold token.

My assumption was that with that I was able to hold the whole context and continue later.

But I missed one important detail, which is the call stack that happens in the case of branch nodes (AND's and OR's). On processing those nodes, the program adds a stack position, and then, when my resolver response is supposed to pause, it just goes one step up in the stack and triggers the next node after the branch node, and that happens before the batch process kicks in.

This issue will break many batch cases that are not in a trivial position (not preceded by any branch node).

One possible solution is to add even more code to keep tracking back the batch hold across many nodes. But this is a considerable amount of complexity, I think there might be a better way.

All that to say, its a complicated problem, and I need to spend some time figuring it out, all open for ideas too :)

**Comment by wilkerlucio** [comment]
@fjolne I just pushed some fixes to batching at 8d907f70f32fc3cc8708fc5e1ce28095283c0922. Can you please check if things work as expected for you in this version?

@eneroth

**Comment by wilkerlucio** [comment]
And for more context, the current attempt solution does this:

- When a node needs to hold for batch, it returns a value with the batch details
- In case there is a node stack, the parent (an OR or AND node) will receive the hold, and will also pause, the implementation changed on both AND and OR nodes to support this
- Batches run as usual, but after run, instead of trying to get back in the node it stopped, Pathom now will re-start that graph from the root. Nodes that already ran will be skipped (due to the data being already available).

Still trying to see if this run from root is a perf issue, but will need to experiment more and see how it goes.

**Comment by wilkerlucio** [comment]
I sent the wrong version to test on the previous comment, correct version: fe29d9d3ec89a0321bf20b41a4f2d161f715b80d (also fixed there now)

**Comment by eneroth** [comment]
@wilkerlucio I can't provoke the error anymore, so for our limited test case, it seems good 👍
