### ISSUE TITLE
Possible process error

### ISSUE THREAD

**Issue by wilkerlucio** [wilkerlucio/pathom3#52]
This is an issue under investigation reported by Mark Addleman:

```hi @wilkerlucio Today has been pretty hectic for me and it seems you and I will have trouble connecting in a live session.  I wrote up my investigation into the problem here https://docs.google.com/document/d/1tSYSg0IQPpvrS4u-KG5x3tvJfls_dmJfhhY2gO4UF7E/edit?usp=sharing

I'd love to be able to give you a small repro case but I can't figure out how to reproduce the problem under simple conditions```

**Comment by markaddleman** [comment]
I have a repro case.  [https://gist.github.com/markaddleman/c9d9f7860ad52868656addc56d8ee74c](gist)

You'll see that by including the "pega-entities" resolver in the environment, the planner cannot produce a plan.  When that resolver is not included in the environment, the query is executed and returns a successful result.
