### ISSUE TITLE
Priorization bug

### ISSUE THREAD

**Issue by mauricioszabo** [wilkerlucio/pathom3#53]
Following the #48 bug, this code also doesn't obey priorization:

```clojure
(pco/defresolver default-namespaces [env {:keys [repl/kind]}]
  {::pco/output [:repl/namespace] ::pco/priority 0}

  (prn :PRIORITY-0))

(pco/defresolver namespace-from-editor [inputs]
  {::pco/input [{:editor/ns [:text/contents]}]
   ::pco/output [:repl/namespace]
   ::pco/priority 1}

  (prn :PRIORITY-1)
  {:repl/namespace (-> inputs :editor/ns :text/contents symbol)})

(pco/defresolver repl-kind-from-config [{:config/keys [eval-as]}]
  {::pco/output [:repl/kind] ::pco/priority 1}

  {:repl/kind eval-as})

(pco/defresolver seed-data [{:keys [seed]} _]
  {::pco/output (->> schemas/registry keys (remove #{:map}) vec)
   ::pco/priority 99}
  seed)

#_
(-> [seed-data
     repl-kind-from-config
     default-namespaces namespace-from-editor]
    indexes/register
    (plugin/register (plugins/attribute-errors-plugin))
    (assoc :seed {:repl/kind :clj
                  :editor/ns {:text/contents "some-ns"}})
    (eql/process [:repl/namespace]))
```

The last code prints `:PRIORITY-0`  first

If I remove the `repl-kind-from-config` resolver from the list, the priorization works correctly - even considering that this resolver is not being called on this query.

**Comment by wilkerlucio** [comment]
As noted with conversations with @mauricioszabo, this is not a bug, the algorithm is working as intended.

The issue is more on the design and fundamentals, the problem of prioritization on Pathom graphs is still an open question. I encourage the discussion to continue at https://github.com/wilkerlucio/pathom3/discussions/57

**Comment by mauricioszabo** [comment]
Do you think it's a good idea to add something on the documentation, explaining the issue? Priorization, as it's done today, can lead people to think that if they prioritize one resolver in place of other it'll _always_ run first, and it's not really the case

**Comment by wilkerlucio** [comment]
Makes sense, considering that I just extended the prioritization docs https://pathom3.wsscode.com/docs/resolvers/#prioritization

Now it includes an example of the edge case.
