### ISSUE TITLE
Feasibility of more complex queries

### ISSUE THREAD

**Issue by hsartoris-bard** [wilkerlucio/pathom3#7]
I'm using Pathom 2 and wondering if you have plans for 'natively' handling complex queries. 

There are a couple of reasons why this might make sense:
1. Writing code to strip a 'dumb' query result of unwanted values reifies the structure of the data outside of the query. This can introduce a future disconnect between the shape of the data as requested and the shape as needed by the post-processing functions.
2. Having a standard dialect for filtering results could allow for resolvers to take advantage of the requested filters to reduce the scope of the query, when supported by the backend. An example of this is illustrated below.

Let's say I have the following query:
```clojure
[{:users/list [:user/email :user/employeeType :user/groups]}]
; yields:
{:users/list
 [#:user{:email "jdoe@domain"
         :employeeType "staff"
         :groups [{:group/email "a-group@domain"}
                  {:group/email "b-group@domain"}]}
  #:user{:email "jpublic@domain"
         :employeeType "faculty"
         :groups [{:group/email "a-group@domain"}]}]}
```
Well, now I'd like to formulate a query to find users who are either faculty or staff, and are members of "a-group@domain". I can solve part of this problem with parameterization on `:users/list`:
```clojure
[{(:users/list {:filter "(|(employeeType=staff)(employeeType=faculty))"}) .....
```
And, once I've implemented the logic to pick that up, that's all well and good. However, the part where I restrict to users who are members of "a-group@domain" is trickier. I created a transformer to filter results based on parameters (not the same as the logic catching the above parameterization), and then I can do something like this:
```clojure
[{(:users/list {:filter "(|(employeeType=staff)(employeeType=faculty))"})
  [:user/email (:user/groups {:group/email "b-group@domain"})]}]
```
And have the resolver for `:user/groups` return `:no-match` rather than a value when the filter is not satisfied. I then modified the Pathom parser to short-circuit when `:no-match` is discovered as a value for a child and immediately return the same, and also to strip vector results of that keyword. This works: the above query will then produce
```clojure
{:users/list
 [#:user{:email "jdoe@domain"
         :groups [{:group/email "b-group@domain"}]}]}
```
However, there is no easy way to invert this query that I can think of; i.e., it is nontrivial to ask "what users that are either faculty or staff are *not* members of b-group@domain" - not without going and implementing very specific logic to answer parts of the question, although all of the predicates involved are general. Moreover, I'm already up to two different approaches for filtering, as each one is ad-hoc. The only real difference is that the resolver providing `:users/list` is capable of restricting its queries ahead of time, whereas the groups resolver does not know how to do that. However, these shouldn't ultimately be a difference in terms of interface, imo. In an ideal world, I would be able to define behavior for handling filters on a given resolver if possible given the particular backend, otherwise letting the results be resolved and filtered post-facto by Pathom. 

Interested in any thoughts on how this could be approached. Of course, if I've totally missed something and there's already a better way to do this, I'd love to know.

**Comment by lilactown** [comment]
(I'm going to treat this issue as more of a discussion, so apologies @wilkerlucio if this reply is in the wrong place)

IME things like EQL/GraphQL are purpose-built for arbitrary _selecting_ of attributes, but are not really made for arbitrary filtering/sorting/transforming. At some point it makes sense to recognize that and drop down to something more flexible like Datalog, SQL, or do this filtering programmatically.

Especially with your last use case: "what users that are either faculty or staff are not members of b-group@domain" is exactly the kind of question Datalog is made for:

```
[:find ?email
 :where [?group :group/email "b-group@domain"]
        [?e :groups ?group]
        [?e :email ?email]]
```

Implementing this sort of logic programming within EQL/Pathom seems wildly broadening the scope of the library.

**Comment by wilkerlucio** [comment]
No worries at all @lilactown. I think what you said is very on spot. Parameters can be used for simple filterings, like pagination, but the user starts to push things can get tricky. You can still do it of course by yourself by looking deeper into the query, but these are complex lookups and out of the scope of the core of Pathom.

I hope this clarifies the scope of the library for you @hsartoris-bard.

Also, I like to suggest the usage of the new Discussions tab in the project for this kind of thing, and reserve issues for bugs.

**Comment by hsartoris-bard** [comment]
@lilactown & @wilkerlucio thanks for the clarification and suggestion!
