### ISSUE TITLE
Add config to make "throw on missing" optional

### ISSUE THREAD

**Issue by wilkerlucio** [wilkerlucio/pathom3#74]
In the new strict mode, an attribute failure may happen because:

1. Attribute is unknown in the index
2. Attribute exists in the index, but available data isn't enough to reach it
3. The resolver responsible for the attribute did throw an exception
4. The resolver didn't return a key with that attribute (which is different from a key with a `nil` value, which is a valid response)

For strict mode cases, 1 to 3 will always get an exception up, but case 4 is arguable.

We can add a config option like `:pathom/throw-on-attribute-missing?`, which defaults to `true` in strict mode but can be turned off by the user.

**Comment by eneroth** [comment]
Sounds good. It's a bit of a pain currently to model permissions. I.e., you'll get the contents if you have all the permissions, but getting nothing (except maybe an ID), or a partial response, is still a valid response.

We've solved it temporarily by sticking a `pco/?` on every field in every query. It has the added downside of making the queries larger on the wire, as well.

**Comment by wilkerlucio** [comment]
Hello @eneroth, in this case, why not use the lenient mode?

**Comment by wilkerlucio** [comment]
A concern I have about this is that adding knobs will make the error handling more complex and harder to understand, also when connecting multiple Pathom instances, could be strange to have parts of the system take one approach while other parts taking other. So I rather avoid adding things if possible.

**Comment by eneroth** [comment]
Sorry, I may have misunderstood what you intend to do here, but in lenient mode, a missing attribute still counts as an error, and messes up normalization in the frontend. 

It's still necessary to be able to declare it not an error, or otherwise continue to write queries consisting entirely of question marks.

**Comment by wilkerlucio** [comment]
Hello @eneroth

I just add a new extension point that may help this, based on the later suggestion you had on marking some attributes to not show error. Here is a demo on how to use the new extension point to filter errors for a selection of attributes:

```clojure
(ns com.wsscode.pathom3.demos.error-elider
  (:require [com.wsscode.pathom3.plugin :as p.plugin]
            [com.wsscode.pathom3.connect.operation :as pco]
            [com.wsscode.pathom3.connect.indexes :as pci]
            [com.wsscode.pathom3.interface.eql :as p.eql]))

(defn elide-private-errors [silent-attribute-errors]
  {::p.plugin/id
   `elide-private-errors

   :com.wsscode.pathom3.error/wrap-attribute-error
   (fn [attribute-error]
     (fn [entity attribute]
       (when-not (contains? silent-attribute-errors attribute)
         (attribute-error entity attribute))))})

(pco/defresolver error-resolver [{::keys []}]
  (throw (ex-info "Error" {}))
  {:foo "bar"})

(def env
  (-> {:com.wsscode.pathom3.error/lenient-mode? true}
      (p.plugin/register (elide-private-errors #{:foo}))
      (pci/register [error-resolver])))

(comment
  (p.eql/process env [:foo :foo2]))
```

Please let me know if that is sufficient to handle your case, or we can iterate on it before release.

Cheers.

**Comment by wilkerlucio** [comment]
You need to use master for this to work (to get the new extension point).

**Comment by wilkerlucio** [comment]
@eneroth I like to check if this still a need for you, does the extension points solve your case, or there still something related to this issue that you think needs fixing?

**Comment by eneroth** [comment]
Hey @wilkerlucio, thanks for pinging. I forgot about this, as we have a (rather icky) postwalk that hides the problem.

I will spike this tomorrow and report back.

**Comment by eneroth** [comment]
Thank you @wilkerlucio, it works exactly as advertised!

**Comment by wilkerlucio** [comment]
Awesome :)
